### ISSUE TITLE
Doesn't work on simple strings in Go

### ISSUE THREAD

**Issue by nicksnyder** [lguychard/sourcegraph-string-references#1]
https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go#L18:34&tab=references

![image](https://user-images.githubusercontent.com/754768/47465930-c59f6980-d7a3-11e8-8137-9737ccd73888.png)

**Comment by lguychard** [comment]
![image](https://user-images.githubusercontent.com/1741180/47466851-520c5500-d7c1-11e8-8a98-c035c7dc883a.png)

Linked to the presence of whitespace in the string
