### ISSUE TITLE
Find references for outer most string

### ISSUE THREAD

**Issue by nicksnyder** [lguychard/sourcegraph-string-references#2]
Expected:
I would expect to be able to find references on the string `"jumped 'over'"`.

Actual:
Hovering on `over` finds references for the string of `'over'` and hovering over `jumped` doesn't find any references at all.

https://sourcegraph.com/github.com/lguychard/sourcegraph-string-references@master/-/blob/src/util.test.ts#L24:54

![image](https://user-images.githubusercontent.com/754768/47466997-eb7b3d00-d7a8-11e8-9ed5-040a7aaa393d.png)

**Comment by lguychard** [comment]
@nicksnyder fixed in 1.0.28

![image](https://user-images.githubusercontent.com/1741180/47468163-cf3ac880-d7c7-11e8-8c76-8eefc188dc78.png)
