### ISSUE TITLE
Handle escaped double quotes in double quoted strings

### ISSUE THREAD

**Issue by nicksnyder** [lguychard/sourcegraph-string-references#3]
Expected:
Hovering anywhere over `"export $1=\"${!1}\"; "` should find references for the string `export $1="${!1}"; `.

Actual:
It treats any escaped double quote as terminating the string.

https://sourcegraph.com/github.com/golang/go/-/blob/misc/arm/a#L23:9

![image](https://user-images.githubusercontent.com/754768/47467269-6e50c780-d7aa-11e8-837c-8f6343f82be5.png)

**Comment by lguychard** [comment]
![image](https://user-images.githubusercontent.com/1741180/47468123-9b5fa300-d7c7-11e8-90ea-3fb9629a1a99.png)

@nicksnyder fixed in 1.0.28
