### ISSUE TITLE
Support configurable definitions/references

### ISSUE THREAD

**Issue by nicksnyder** [lguychard/sourcegraph-string-references#5]
I would love to be able to solve the original use case specced out in https://github.com/sourcegraph/sourcegraph-extension-api/issues/85#issue-371350235 through this extension in a configurable way.

Imagine I could give this extension a configuration like this:

```json
[
  {
    "definitions": [
      {
        "capture": ".HandleFunc(\"([^\"]+)\")",
        "search": ".HandleFunc(\"$1\")"
      },
      {
        "capture": ".Handle(\"([^\"]+)\")",
        "search": ".Handle(\"$1\")"
      }
    ],
    "references": [
      {
        "capture": "http.Get(\"([^\"]+)\")",
        "search": "http.Get(\"$1\")"
      },
      {
        "capture": "http.Post(\"([^\"]+)\")",
        "search": "http.Post(\"$1\")"
      },
      {
        "capture": "http.PostForm(\"([^\"]+)\")",
        "search": "http.PostForm(\"$1\")"
      },
      {
        "capture": "http.NewRequest([^,]+, \"([^\"]+)\")",
        "search": "http.NewRequest([^,]+, \"$1\")"
      }
    ]
  }
]

```

If a line matches a capture regex from `definitions` then you can find references on it and the result set is the union of searches in the `references` with the $1 replaced with the value captured from the definition regex.

Similarly, if a line matches a capture regex from `references` then you can do the same reference search as above and also you can perform a "Go to definition" action that searches for definitions.

**Comment by nicksnyder** [comment]
**note**: don't treat the above as a strict spec, or rigorous example (e.g. I am sure I messed up some json/regex escaping somewhere). If you can think of a better way to accomplish what I am asking for, let's discuss it.

**Comment by lguychard** [comment]
I like how this "extensibility through configuration" would allow to handle much more than HTTP routes. Another use case that comes to mind is build scripts (jump to definition for make tasks, or scripts referenced in a Travis.yml...)

However, this is quite different from just a "String Reference Finder", since it essentially amounts to adding code intelligence for arbitrary custom entities, and I would argue that both extensions actually have a use case ("String Reference Finder" & "Custom Entities").

Thoughts?

**Comment by lguychard** [comment]
@nicksnyder came up with an [implementation](https://github.com/lguychard/sourcegraph-string-references/commit/a2e99a6ab9ff421314149c9252302d311d9e3b39) for this use case, which is for now published as a [separate extension](https://sourcegraph.com/extensions/lguychard/custom-entities) without breaking the first one.

With the following configuration added to the Sourcegraph extension client settings:

```
"entities": [
    {
      "name": "HTTP Route",
      "preview": ": `\"/$1\"`",
      "definitions": [{
          "search": "/httpPost\\(ctx, req.Repo, \"$1/",
          "capture": "httpPost\\(ctx, req\\.Repo, \"/?([^\"]+)\""
        }],
      "references": [{
          "search": "mux.HandleFunc\\(\\\"\\/$1",
          "capture": "mux.HandleFunc\\(\"/([^\"]+)"
      }],
      "implementations": [],
    }
  ]
```

The extension correctly performs find references / go to definition:

![image](https://user-images.githubusercontent.com/1741180/47526145-e41d6780-d86c-11e8-91c5-2f13c3e8f888.png)

I still reckon this extension is best kept separate from the "String Reference Finder" (in which case I'd probably move it to its own repository). Opinions?

**Comment by nicksnyder** [comment]
Nice! I haven't looked at the code yet, but I think I agree with it being a separate extension and separate repo. I am wondering if we can express the string references behavior as a (default) config in the new extension and get rid of this extension entirely?

What about an extension name like "Regular Expression References", "Regex References" or "Configurable References" ?

**Comment by lguychard** [comment]
Alright, here goes: the "Configurable References" extension now lives [here](https://github.com/lguychard/sourcegraph-configurable-references)

Expressing the string references behaviour through configuration was on my mind as well. I added this default behaviour. Please note that the regexes I used to define string literals may not handle all cases as well as the string references extension - consider them to be a first step to be improved.
